import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {decrypt,unzip,flatten} from '../core.js';
const root=new URL('../',import.meta.url),manifest=JSON.parse(await fs.readFile(new URL('vault/manifest.json',root)));
const key=await crypto.subtle.importKey('raw',Buffer.from(manifest.publicKey,'base64'),{name:'AES-GCM'},false,['decrypt']);
const catalog=await unzip(await decrypt(key,await fs.readFile(new URL('vault/'+manifest.catalog,root))));
const meta=catalog.find(b=>b.key==='theory-50033');
const bank=await unzip(await decrypt(key,await fs.readFile(new URL('vault/'+meta.file,root)))),flat=flatten(bank),q=flat[0];
const associated=flat.find(q=>q.legacyUid&&flat.filter(x=>x.legacyUid===q.legacyUid&&(x.titleText??x.title)===(q.titleText??q.title)).length===1);
assert.equal(new Set(flat.map(q=>q.uid)).size,flat.length);
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const user={id:'22222222-2222-4222-8222-222222222222',email:'qa@example.invalid',aud:'authenticated',role:'authenticated'};
const encode=x=>Buffer.from(JSON.stringify(x)).toString('base64url');
const token=encode({alg:'HS256',typ:'JWT'})+'.'+encode({sub:user.id,role:'authenticated',exp:Math.floor(Date.now()/1000)+3600})+'.qa';
const events=[],errors=[];let pushes=0,pulls=0;
async function until(fn,label){for(let i=0;i<150;i++){if(await fn())return;await new Promise(r=>setTimeout(r,100));}throw Error('Timed out: '+label);}
async function makePage(){
 const context=await browser.newContext({viewport:{width:1440,height:950},serviceWorkers:'block'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/sync-config.js',r=>r.fulfill({contentType:'text/javascript',body:"export const syncConfig={url:'https://demo.supabase.co',publishableKey:'sb_publishable_test',relay:'http://127.0.0.1:4173'};"}));
 await page.route('**/api/cloud?**',async route=>{
  const req=route.request(),url=new URL(req.url()),path=url.searchParams.get('path'),query=new URLSearchParams(url.searchParams.get('query'));let body={};
  if(path.startsWith('/auth/v1/token'))body={access_token:token,refresh_token:'qa-refresh',expires_in:3600,token_type:'bearer',user};
  else if(path==='/auth/v1/user')body=user;
  else if(path.endsWith('/rpc/haixing_push_events')){pushes++;for(const e of req.postDataJSON().batch)if(!events.some(x=>x.event_id===e.id))events.push({seq:events.length+1,event_id:e.id,device:e.device,clock:e.clock,payload:e.payload});body=null;}
  else if(path==='/rest/v1/haixing_events'){pulls++;const cursor=Number((query.get('seq')||'gt.0').slice(3));body=events.filter(e=>e.seq>cursor);}
  await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});
 });
 await page.goto('http://127.0.0.1:4173/#profile');await page.getByRole('button',{name:'登录 / 注册',exact:true}).click();await page.locator('#cloud-email').fill(user.email);await page.locator('#cloud-password').fill('qa-password');await page.getByRole('button',{name:'登录',exact:true}).click();await page.getByRole('button',{name:'立即同步',exact:true}).waitFor();await page.waitForFunction(()=>document.querySelector('.status-dot')?.textContent==='已同步');
 return page;
}
async function sync(page){await page.locator('[data-action=cloud-sync]').click();await page.waitForFunction(()=>!document.querySelector('[data-action=cloud-sync]')?.disabled);}
const read=(page,store,key)=>page.evaluate(async({store,key})=>{const c=await import('/core.js');return c.get(store,key);},{store,key});
try{
 await fs.mkdir('test-results',{recursive:true});const a=await makePage(),b=await makePage();
 await a.getByRole('button',{name:'返回学习概览',exact:true}).click();await a.waitForURL('**/#home');await a.getByRole('button',{name:'打开个人主页',exact:true}).click();await a.waitForURL('**/#profile');
 await a.locator('[data-action=edit-profile]').click();await a.locator('#profile-nickname').fill('远航学员');await a.locator('#profile-bio').fill('每天前进一点，向着下一程。');await a.locator('[data-action=pick-avatar][data-avatar="🧭"]').click();await a.locator('[data-action=save-profile]').click();await a.locator('.profile-heading h1').filter({hasText:'远航学员'}).waitFor();await sync(a);await sync(b);await until(async()=> (await read(b,'settings','user-profile'))?.nickname==='远航学员','profile sync');
 await a.reload();await a.locator('.profile-heading h1').filter({hasText:'远航学员'}).waitFor();await a.locator('[data-action=edit-profile]').click();await a.locator('#profile-avatar-file').setInputFiles(new URL('../icon-192.png',import.meta.url).pathname.replace(/^\//,''));await until(()=>a.locator('#profile-avatar-preview img').count(),'uploaded avatar');await a.locator('[data-action=save-profile]').click();await a.locator('.profile-intro .avatar img').waitFor();await sync(a);await sync(b);await until(async()=> (await read(b,'settings','user-profile'))?.avatar?.startsWith('data:image/webp'),'photo sync');await a.screenshot({path:'test-results/profile-desktop.png',fullPage:true});
 await a.goto('http://127.0.0.1:4173/#bank/'+meta.key);await a.locator('.chapter-row').first().waitFor();assert.equal(await a.locator('.chapter-group [data-action=custom]').count(),0);assert.equal(await a.locator('.custom-tools [data-action=custom]').count(),2);assert.equal(await a.locator('.chapter-ring').count(),bank.chapters.length);await a.waitForTimeout(900);
 await a.evaluate(()=>{window.__main=document.querySelector('.main');window.__chapter=document.querySelector('.chapter-row');window.scrollTo(0,document.body.scrollHeight-950);window.__y=scrollY;window.__mutations=0;new MutationObserver(r=>window.__mutations+=r.length).observe(document.querySelector('.main'),{subtree:true,childList:true,attributes:true,characterData:true});});const countBefore=pushes,pullsBefore=pulls;await a.waitForTimeout(11500);
 const quiet=await a.evaluate(()=>({same:window.__main===document.querySelector('.main')&&window.__chapter===document.querySelector('.chapter-row'),scroll:Math.abs(scrollY-window.__y),mutations:window.__mutations,y:scrollY}));assert.ok(quiet.same);assert.ok(quiet.y>500);assert.ok(quiet.scroll<2);assert.equal(quiet.mutations,0);assert.equal(pushes,countBefore);assert.ok(pulls>pullsBefore);
 await b.evaluate(async(q)=>{const c=await import('/core.js');await c.put('records',q.uid,{uid:q.uid,bank:q.bank,attempts:1,correctCount:1,lastAt:Date.now()});},{uid:q.uid,bank:bank.key});await sync(b);await until(async()=> (await a.locator('.chapter-row small').first().textContent()).includes('已刷 1 /'),'remote progress');assert.ok(await a.evaluate(()=>Math.abs(scrollY-window.__y)<2&&window.__chapter===document.querySelector('.chapter-row')));
 await a.reload();await a.locator('.chapter-row').first().waitFor();await a.waitForTimeout(400);assert.ok(Math.abs(await a.evaluate(()=>scrollY)-quiet.y)<2);
 await a.locator('[data-action=custom]').first().click();await a.locator('#custom-name').fill('每日 3 题');await a.locator('#custom-count').fill('3');await a.locator('#custom-order').selectOption('sequence');await b.evaluate(async()=>{const c=await import('/core.js');await c.put('records','remote:extra',{uid:'remote:extra',attempts:1});});await sync(b);await a.waitForTimeout(6500);assert.equal(await a.locator('#custom-name').inputValue(),'每日 3 题');await a.locator('[data-action=save-plan]').click();await a.locator('.saved-plans').filter({hasText:'每日 3 题'}).waitFor();await a.locator('.saved-plans [data-action=run-plan]').click();await a.waitForURL('**/#practice');await a.locator('.options').waitFor();for(const answer of q.answer.replace(/[^A-F]/g,''))await a.locator('[data-action=option][data-value='+answer+']').click();if(await a.locator('[data-action=confirm-answer]').count())await a.locator('[data-action=confirm-answer]').click();await until(async()=> (await read(a,'records',q.uid))?.attempts===2,'actual answer saved');await a.locator('[data-action=step][data-delta="1"]').click();await a.locator('[data-action=leave-practice]').click();await a.waitForURL('**/#bank/*');await a.locator('.saved-plans [data-action=run-plan]').click();await a.waitForURL('**/#practice');await until(async()=> (await read(a,'sessions','active'))?.index===1,'practice continuation');await a.locator('[data-action=leave-practice]').click();await a.waitForURL('**/#bank/*');
 const search=a.locator('#question-search');await search.fill('海图');await a.waitForTimeout(250);await search.focus();await a.evaluate(()=>document.querySelector('#question-search').setSelectionRange(1,1));await b.evaluate(async()=>{const c=await import('/core.js');await c.put('records','remote:focus',{uid:'remote:focus',attempts:1});});await sync(b);await a.waitForTimeout(6500);assert.equal(await search.inputValue(),'海图');assert.ok(await a.evaluate(()=>document.activeElement.id==='question-search'&&document.activeElement.selectionStart===1));await a.reload();await a.locator('#question-search-results .list-row').first().waitFor();assert.equal(await search.inputValue(),'海图');await search.fill('');await a.waitForTimeout(250);await a.screenshot({path:'test-results/chapters-desktop.png',fullPage:true});
 await b.evaluate(async(q)=>{const c=await import('/core.js');await c.put('records',q.legacyUid,{uid:q.legacyUid,bank:q.bank,title:q.title,attempts:1,correctCount:1});},{legacyUid:associated.legacyUid,bank:bank.key,title:associated.titleText??associated.title});await sync(b);await until(async()=> (await read(a,'records',associated.uid))?.attempts===1,'legacy associated record migration');assert.equal(await read(a,'records',associated.legacyUid),undefined);await a.locator('.chapter-row small').last().filter({hasText:'已刷 1 / 390'}).waitFor();
 await a.setViewportSize({width:390,height:844});await a.locator('[data-action=nav][data-route=profile]').filter({has:a.locator('span')}).last().click();await a.waitForURL('**/#profile');await a.locator('.profile-intro').waitFor();assert.ok(await a.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await a.screenshot({path:'test-results/profile-mobile.png',fullPage:true});await a.locator('[data-action=edit-profile]').click();assert.ok(await a.evaluate(()=>document.querySelector('#modal').getBoundingClientRect().width<=innerWidth));await a.screenshot({path:'test-results/profile-editor-mobile.png'});await a.locator('[data-action=close-modal]').click();await a.locator('[data-action=theme]').first().click();await a.waitForFunction(()=>document.body.classList.contains('dark'));await a.screenshot({path:'test-results/profile-dark-mobile.png',fullPage:true});
 assert.ok(!/本站没有|不构成|不能替代|人工智能|仅供参考/.test(await a.locator('.main').innerText()));assert.deepEqual(errors,[]);
 console.log(JSON.stringify({realBank:meta.name,chapters:bank.chapters.length,quiet,profileAndPhotoSync:true,scrollRestored:true,inputPreserved:true,customPlanAndResume:true,mobileAndDark:true,pushes,pulls,errors}));
}finally{await browser.close();}
